### ISSUE TITLE
Ошибки нельзя логировать в System.out, вообще не используем System.out, логируем в logger.error()

### ISSUE THREAD

**Issue by boris-dev** [ikvwar7/liga-internship#10]
https://github.com/ikvwar7/liga-internship/blob/541f7eab3ac174c26bd2acb0fd1a98acab928d44/javacore-song-task/src/main/java/ru/liga/songtask/analiz/WriteToFile.java#L11

**Comment by ikvwar7** [comment]
Всё исправил (исправил раньше, забыл здесь отписаться)
