### ISSUE TITLE
Метод нарушает конвенцию без видимой причины, нужно использовать camel case для методов

### ISSUE THREAD

**Issue by boris-dev** [ikvwar7/liga-internship#12]
https://github.com/ikvwar7/liga-internship/blob/541f7eab3ac174c26bd2acb0fd1a98acab928d44/javacore-song-task/src/main/java/ru/liga/songtask/analiz/Change.java#L20

**Comment by ikvwar7** [comment]
Всё исправил (исправил раньше, забыл здесь отписаться)
