### ISSUE TITLE
Определение переменной должно быть как можно глубже в использовании

### ISSUE THREAD

**Issue by boris-dev** [ikvwar7/liga-internship#2]
т.е. не стоит выносить их выше чем нужно для их использования, это ухудшает читабельность

https://github.com/ikvwar7/liga-internship/blob/541f7eab3ac174c26bd2acb0fd1a98acab928d44/javacore-song-task/src/main/java/ru/liga/songtask/analiz/MyClass.java#L24

**Comment by ikvwar7** [comment]
Всё исправил (исправил раньше, забыл здесь отписаться)
