### ISSUE TITLE
Необходимо форматировать код! Ctrl+Alt+L

### ISSUE THREAD

**Issue by boris-dev** [ikvwar7/liga-internship#3]
https://github.com/ikvwar7/liga-internship/blob/541f7eab3ac174c26bd2acb0fd1a98acab928d44/javacore-song-task/src/main/java/ru/liga/songtask/analiz/MyClass.java#L27

**Comment by ikvwar7** [comment]
Всё исправил (исправил раньше, забыл здесь отписаться)
