### ISSUE TITLE
В таких случаях лучше использовать foreach по Set-у тогда не будет лишнего каста и масивов от object

### ISSUE THREAD

**Issue by boris-dev** [ikvwar7/liga-internship#6]
https://github.com/ikvwar7/liga-internship/blob/541f7eab3ac174c26bd2acb0fd1a98acab928d44/javacore-song-task/src/main/java/ru/liga/songtask/analiz/Output.java#L30

**Comment by ikvwar7** [comment]
Всё исправил (исправил раньше, забыл здесь отписаться)
