### ISSUE TITLE
Непонятная сигнатура метода, либо javadoc, но лучше найти подходящее название

### ISSUE THREAD

**Issue by boris-dev** [ikvwar7/liga-internship#9]
https://github.com/ikvwar7/liga-internship/blob/541f7eab3ac174c26bd2acb0fd1a98acab928d44/javacore-song-task/src/main/java/ru/liga/songtask/analiz/Output.java#L63

**Comment by ikvwar7** [comment]
Всё исправил (исправил раньше, забыл здесь отписаться)
